[phases.setup]
nixPkgs = ["php83", "php83Extensions.curl", "php83Extensions.mbstring", "php83Extensions.intl"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php spark serve --host 0.0.0.0 --port ${PORT:-8080}"